services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:5000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - ml-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ML_SERVICE_URL=http://ml-service:8000
      - ConnectionStrings__DefaultConnection=Data Source=data.db

  ml-service:
    build:
      context: ./ml-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./ml-service/models:/app/models
      - ./ml-service/data:/app/data

volumes:
  ml_models:
  app_data:
